
import argparse
import os
from importlib.resources import files

def greet():
    print("Hello, my name is Clank.")
    print("What can I do for you?")

def prepare_files(prefix, number_of_problems):
    print("Preparing files")

    template_path = files('clank.resources').joinpath('CF_template.cpp')
    # print(template_path)
    with open(template_path, 'r') as template_file:
        template_content = template_file.read()

    for i in range(number_of_problems):
        path = prefix + chr(i + ord('A')) + ".cpp"

        with open(path, 'w') as dest_file:
            dest_file.write("// This file was generated by Clank\n")
            dest_file.write(template_content)

        print(f"Created {path} file")

def clean_bin_files():
    for file in os.listdir('.'):
        new_path = file + ".cpp"
        if os.path.isfile(new_path):
            os.remove(file)
            print(f"{file} removed")

def main():
    parser = argparse.ArgumentParser(description = "Tool for automating competitive programming related tasks")

    parser.add_argument("--greet", action="store_true", help="Print greeting message")
    parser.add_argument("--cf", nargs = 2, type = str, help="Create files for contest")
    parser.add_argument("--clean", action="store_true", help="clean binary files")

    args = parser.parse_args()

    if args.greet:
        greet()

    if args.clean:
        clean_bin_files()
    
    if args.cf:
        prefix, number_of_problems = args.cf
        prepare_files(prefix, int(number_of_problems))