from importlib.resources import files

def create_task_init_parser(parser):
    subparser = parser.add_parser("create", help="Create file for certain task")
    subparser.add_argument("name", type=str, help="Filename")

def create_task(filename):
    print("Creating file")

    template_path = files('clank.resources').joinpath('CPP_template.cpp')
    with open(template_path, 'r') as template_file:
        template_content = template_file.read()

    if not filename.endswith(".cpp"):
        filename += ".cpp"

    with open(filename, 'w') as dest_file:
            dest_file.write("// Template generated by Clank\n")
            dest_file.write(template_content)

    print(f"Created {filename} file")