from importlib.resources import files

def prepare_files(prefix, number_of_problems):
    print("Preparing files")

    template_path = files('clank.resources').joinpath('CF_template.cpp')
    # print(template_path)
    with open(template_path, 'r') as template_file:
        template_content = template_file.read()

    for i in range(number_of_problems):
        path = prefix + chr(i + ord('A')) + ".cpp"

        with open(path, 'w') as dest_file:
            dest_file.write("// This file was generated by Clank\n")
            dest_file.write(template_content)

        print(f"Created {path} file")